import { PollQuestion_t, PollResponse_t } from "$/types/documents"

export type UserQuestionInfo = PollQuestion_t & {
	userResponse?: string
}

export const professionList = [
	"Astronaut",
	"Accountant",
	"Attorney",
	"Audio Engineer",
	"Auditor",
	"Aviator",
	"Adventurer",
	"Archer",
	"Architect",
	"Aerospace Engineer",
	"Arbiter",
	"Actor",
	"Advocate",
	"Antique Collector",

	"Balloon Enthusiast",
	"Barista",
	"Baker",
	"Burrito-maker",
	"Baron",
	"Barbarian",
	"Bard",
	"Beekeeper",
	"Bingo Player",
	"Bully",
	"Basketballer",
	"Boxer",
	"Businessman",
	"Bunny",
	"Bugler",
	"Bartender",
	"Babysitter",
	"Bowling Ball",
	"Blade",

	"Cook",
	"Criminal",
	"Creature",
	"Calligrapher",
	"Carpenter",
	"Clocksmith",
	"Challenger",
	"Carver",
	"Copilot",
	"Cabin Stewardess",
	"Captain",
	"Ceramic Sculptor",
	"Cleric",
	"Child",
	"Colonel",
	"Color Commentator",
	"Conductor",
	"Chaos Monkey",
	"Collection of Squirrels Pretending to be a Human",

	"Dentist",
	"Dermatologist",
	"Doctor",
	"Dabbler",
	"Driver",
	"Demon Mage",
	"Dancer",
	"Druid",
	"Detective",
	"Dry Cleaner",

	"Egyptologist",
	"Entertainer",
	"Electrician",
	"Executioner",
	"Explorer",
	"EMT",
	"Evil Mastermind",
	"Engineer",
	"Estate Planner",
	"Environmental Scientist",

	"Farmer",
	"Food Vlogger",
	"Fool",
	"Fury",
	"Fake Teeth Salesman",
	"Fighter",
	"Fellow",

	"Gamer",
	"Gobbler",
	"Glassblower",
	"Golem",
	"Graphic Designer",
	"Gardener",
	"Guide",
	"Guy",
	"German Teacher",
	"Goalie",
	"Groundskeeper",
	"Goblin",

	"Hairdresser",
	"Hatmaker",
	"Hooligan",
	"Harbinger",
	"Historian",
	"Hero",
	"Hostage Negotiator",

	"Investigative Journalist",
	"Intern",
	"Interloper",
	"Instructor",
	"Illustrator",
	"IT Specialist",
	"Interpreter",
	"Imbiber",
	"Imbecile",
	"Ice Sculptor",
	"Igloo Architect",
	"Indigo Bunting",

	"Jester",
	"Jimbob",
	"Janitor",
	"Jailkeeper",
	"Jam Maker",
	"Jeweler",
	"Jovial Guy",
	"Judge",
	"Juror",

	"Killer",
	"Keebler Elf",
	"Keyboard Technician",
	"Kangaroo Boxer",
	"Kinesiologist",
	"Kickboxer",
	"Klaxon Tester",
	"Karate Kid",
	"Kool-Aid Man",

	"Locksmith",
	"Loser",
	"Lifeguard",
	"Lover",
	"Lawyer",
	"Loiterer",
	"Lunatic",
	"Lollygagger",
	"Landlord",
	"Loanshark",
	"Labeler",
	"Lucky One",
	"Laminator",
	"Laser Tag Operator",
	"Leprechaun",
	"Leatherworker",

	"Man",
	"Moonman",
	"Monk",
	"Manager",
	"Musician",
	"Model",
	"Marketing Agent",
	"Marriage Counselor",
	"Marty McFly",
	"Mailman",
	"Moderator",
	"Mate",
	"Martial Law",

	"Ne'er-do-well",
	"Nail Technician",
	"Nocturnal",
	"NASCAR Driver",
	"Naval Officer",
	"Narrator",
	"Naturally Gifted Child",
	"Nurse",
	"Nutritionist",
	"Naturalist",
	"Neuroscientist",
	"Neurologist",

	"Optometrist",
	"Orthodontist",
	"Ophthalmologist",
	"Oceanographer",
	"Orange Power Ranger",
	"Office Worker",
	"Officer",
	"Operator",
	"Organic Chemist",
	"Opera Singer",
	"Oobleck Salesman",
	"Ornery Old Man",
	"Orator",
	"Orchestra",
	"Order",

	"Philosopher",
	"Plant Scientist",
	"Paramedic",
	"Pharmacist",
	"Psychopath",
	"Psychologist",
	"Plumber",
	"Practical Joker",
	"Paladin",
	"Photographer",
	"Police Officer",
	"President",
	"Politician",
	"Poet",
	"Primordial Being",
	"Professor",
	"Piano Tuner",

	"Quality Assurance Tester",
	"Quilter",
	"Quetzalcōātl",
	"Quacking Duck",
	"Quarantine Supervisor",
	"Quartermaster",
	"Quark Researcher",

	"Rabbi",
	"Roman Catholic",
	"Roman Senator",
	"Radioshack Manager",
	"Restaurant Owner",
	"Ronald McDonald",
	"Reader",
	"Racecar",
	"Radiologist",
	"Ranger",
	"Rook",
	"Rogue",
	"Robocop",
	"Robot",
	"Rancher",
	"Rapper",

	"Stenographer",
	"Skydiver",
	"Scuba Diver",
	"Silly Person",
	"Spaceman",
	"Scientist",
	"Superhero",
	"Sorceror",
	"Supervisor",
	"Skeleton King",
	"Spanish Inquisitor",
	"Summoner",
	"Software Engineer",
	"Swordsmith",
	"Saxophonist",
	"Stormchaser",
	"Squirrel",

	"Trader",
	"Traitor",
	"Tax Accountant",
	"Tailor",
	"Theologian",
	"Tennis Champion",
	"Tree",
	"Tattoo Artist",
	"TED Talker",
	"Teamaker",
	"Tap Dancer",
	"Talk Show Host",
	"Telemarketer",
	"Teller",
	"Truth",
	"The Pope",
	"Theater Kid",
	"Therapist",
	"Tinkerer",

	"Umbrella",
	"Usurper",
	"Urban Planner",
	"Uncle",
	"Umpire",
	"Undercover Agent",
	"Used Car Salesman",

	"Ventriloquist",
	"Veterinary",
	"Veteran",
	"Vacuum",
	"Vortigaunt",
	"Valet",
	"Valve",
	"Vanguard",
	"Vehicle Inspector",
	"Vendor",
	"Video Editor",
	"Violinist",
	"VIP",
	"Varsity Player",
	"Voiceover Artist",

	"Werewolf",
	"Washer",
	"Wendigo",
	"Window Washer",
	"Welder",
	"Whitecollar Criminal",
	"Warlock",
	"Wizard",
	"Warrior",
	"Whaler",
	"Web Developer",
	"Woodworker",
	"Wailer",
	"Warden",
	"Wilderness Expert",
	"Weightlifter",
	"Wimbledon Marshal",
	"Wax Statue",
	"Waiter",
	"Waning Moon Inspector",
	"Woman",
	"Watcher",

	"Xylophonist",
	"Xenobiologist",
	"X-Ray Technican",
	"Xtreme Flavour Blasted Chedder Goldfish Cracker",
	"Xerox Repairman",

	"Yodeler",
	"Yacht Driver",
	"Yahtzee Player",
	"Youth Pastor",
	"Yard Worker",
	"Yarn Weaver",
	"Yo-yo Prodigy",

	"Zombie",
	"Zookeeper",
	"Zebra",
	"Zoning Regulator",
	"Zoologist",
	"Zinc Miner",
	"Zorro",
]


export const qualifierList = [
	"of the Starways",
	"of the Universe",
	"of the Circus",
	"of the Digital Age",
	"of the Automatons",
	"of the Autobots",
	"of the Decepticons",
	"of the Dead",
	'of the Sun',
	"of the Moon",
	"of the Empire",
	"of the Apocalypse",
	"of the Force",
	"of the Last Light",
	"of the Mines",
	"of the Caves",
	"of the Orient",
	"of the Mountains",
	"of the Void",
	"of the Abyss",
	"of the Rails",
	"of the Galaxy",
	"of the Prophets",
	"of the Hierarchs",
	"of the Matrix",
	"of the Age",
	"of the Era",
	"of the End",
	"of the FBI",

	"of Command",
	"of Frost",
	"of Vertigo",
	"of Defense",
	"of Pangaea",
	"of Paris",
	"of Zion",
	"of Contraband",
	"of Conquest",
	"of Vibrant Days",
	"of Existence",
	"of Exile",
	"of All Yet to Come",
	"of Last Thursday",
	"of Symmetry",

	"in Orbit",
	"of Starfleet",
	"in France",
	"in Color",
	"in Another Life",
	"in Defense of the Accused",
	"in Place of the Amateur",

	"for all Time",
	"for all Mankind",
	"for all the Fallen",
	"for all Who Remain",

	"at Work",
	"With a Rat in his Hat",
	"Who is Out of Ideas",
	"Who Fears No Man",
	"Who Fears Only One Man",
	"Who Fears Between Three and Seven Men",
	"Who Loves Eggs",
	"Who is Colorblind",
	"Who was There When it Happened",
	"Who Will Not be Stopped",
]
